### ISSUE TITLE
Erro Baixar Boleto

### ISSUE THREAD

**Issue by AlbertoAlfredo** [marquesjuniorpalmas/webservice-banco-brasil#2]
Eu estou com um problema no baixa e edição de boletos, tanto com o código daqui quanto com o código legado que peguei aqui na empresa que acabei de entrar, todas as requests funcionam menos a baixa e a edição, da código 200, retorna uma string vazia e quando eu puxo o detalhamento do boleto a baixa ou a edição não ocorreram.
Pode me dar uma luz?

**Comment by marquesjuniorpalmas** [comment]
Chama no whats app, 63 992415490
